const movementList = [
  "Front Squat",
  "Bench Press",
  "DeadLift",
  "Overhead Press",
  "Leg Extension",
  "Lying Leg Curl",
  "Pec Deck",
  "Machine Chest Press",
  "Cable Fly",
  "One-Arm Tricep Extension",
  "Reverse Grip Tricep Extension",
  "Tricep Extension",
  "Machine Tricep Pushdown",
  "Dip",
  "Dumbbell Bench Press",
  "Machine High Row",
  "Cable Row",
  "Chin-up",
  "Pull-up",
  "Lat Pulldown",
  "Barbell Curl",
  "Dumbbell Curl",
  "Machine Curl",
  "Lateral Raise(Band)",
  "Machine Shoulder Press",
  "Hanging Leg Raise",
  "Weighted Sit-up"
];

export default movementList;
